<?php
    $this->title('Hello World');
?>
<div class="jumbotron">
    <div class="container">
        <h1>Hello, world!</h1>
        <p>
            Congratulations! You have successfully installed the Mendo Skeleton Application. This skeleton is a starting point for you to begin building your application. If this is your first time with Mendo Framework, checkout out the <a href="#">Getting Started tutorial</a>.
        </p>
        <p>
            <a class="btn btn-primary btn-lg" href="#" role="button">Read the Documentation &raquo;</a>
        </p>
    </div>
</div>
<div class="container">
    <h2 class="text-primary">Why choose Mendo Framework over other frameworks?</h2>
    <br>

    <div class="row">
        <div class="col-md-4">
            <h3>Powerful View Helpers</h3>
            <p>
                View helpers help the view perform certain common tasks. 
                Mendo's view helpers are able to subscribe to the view's events, 
                which allows them to add &lt;head&gt; elements (script, style, title, ...), 
                html attributes, body scripts, etc.
            </p>
            <p><a class="btn btn-default" href="#" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>HMVC - Widgetized Content</h3>
            <p>
                The <i>Request</i> view helper allows you to include the result of a sub-request in the view.
                HMVC increases code modularity, aids re-usability, and maintains a better separation of concerns.
            </p>
            <p><a class="btn btn-default" href="#" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>Great Multilingual Support</h3>
            <p>
                Building multilingual applications has never been so easy:
                the language is automatically fetched from the URL, URL segments can be translated in any language with the bundled I18N routers and view helpers allow you to add the necessary HTML metadata for the current language in use.
            </p>
            <p><a class="btn btn-default" href="#" role="button">Read more &raquo;</a></p>
        </div>
    </div>

    <div class="row">

        <div class="col-md-4">
            <h3>A Better MVC Approach</h3>
            <p>
                According to the original MVC pattern, the controller should not interact with the view.
                Though, all major frameworks seem to contradict this rule.
                The Mendo MVC Framework tend to follow the original pattern with the use of <i>View Models</i>.
            </p>
            <p><a class="btn btn-default" href="#" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>CMS Module (coming soon)</h3>
            <p>
                A simple CMS module, allowing to change the content of the web pages through a WYSIWYG editor, comes as an installable module with the framework.
            </p>
            <p><a class="btn btn-default" href="#" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>&gt;= PHP 5.6</h3>
            <p>
                It's fresh, and makes use of the latest best practices.
            </p>
        </div>
    </div>

    <h2 class="text-primary">What else?</h2>
    <br>

    <div class="row">
        <div class="col-md-4">
            <h3>Straightforward ACL/Auth Component</h3>
            <p>
                You can implement ACL rules on URLs without efforts. 
                Do you have an admin area? Secure access to <i>/admin</i> for administrators only,
                via a simple config rule.
            </p>
            <p><a class="btn btn-default" href="#" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>Convenient Composite Loggers</h3>
            <p>
                Mendo MVC Framework comes with a set of loggers that you can combine 
                for a specific log level.<br>
                Log your messages into your DB, as an email, or you can even tweet them 
                to yourself to take advantage of instant mobile notifications.
            </p>
            <p><a class="btn btn-default" href="#" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>Powerful Input Filters</h3>
            <p>
                Validators and sanitizers help filtering input data.
                Filter funnels allow you to filter a variable through multiple sanitizers and validators at once.
                The <i>Escape</i> helper allows you to escape data in your HTML-templates.<br>
                Input data should be validated/sanitized as soon as possible and escaped as late as possible.
            </p>
            <p><a class="btn btn-default" href="#" role="button">Read more &raquo;</a></p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h3>Reusable Modules</h3>
            <p>
                You can easily create your own custom modules and reuse them across 
                your applications.
            </p>
            <p><a class="btn btn-default" href="#" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>Loosely Coupled Components</h3>
            <p>
                The Mendo Framework comes with a set of components that can be used 
                out of the context of an MVC application.
            </p>
            <p><a class="btn btn-default" href="#" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>Clean Code, KISS, SOLID, Design Patterns, PHP-FIG</h3>
            <p>
                Design patterns and coding standards are used to keep the architecture 
                clean, reusable, maintainable and extensible.
            </p>
        </div>
    </div>

    <hr>

    <footer>
        <p>&copy; Mendoweb 2015</p>
    </footer>
</div> <!-- /container -->