<?php
    $this->title->suffix(' - Mendo Skeleton Application');
    $this->css('//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css');
?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="<?php echo $this->baseUrl; ?>/">Mendo Skeleton Application</a>
        </div>
    </div>
</nav>

<?= $this->content(); ?>
