<?php
    $title->suffix(' - Gobline Skeleton Application');
    $css('//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css');
?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="<?= $basePath ?>/">Gobline Skeleton Application</a>
        </div>
    </div>
</nav>

<?= $this->content(); ?>
