<?php
    $title('Hello World');
?>
<div class="jumbotron">
    <div class="container">
        <h1>Hello, world!</h1>
        <p>
            Congratulations! You have successfully installed the Gobline Skeleton Application. This skeleton is a starting point for you to begin building your application. If this is your first time with Gobline, checkout out the 
            <a href="http://gobline.com/docs/getting-started">Getting Started tutorial</a>.
        </p>
        <p>
            <a class="btn btn-primary btn-lg" href="http://gobline.com/docs" role="button">Read the Documentation &raquo;</a>
        </p>
    </div>
</div>
<div class="container">
    <h2 class="text-primary">Why choose Gobline over other frameworks?</h2>
    <br>

    <div class="row">
        <div class="col-md-4">
            <h3>Powerful View Helpers</h3>
            <p>
                View helpers help the view perform certain common tasks. 
                Gobline's view helpers are able to subscribe to view events, 
                which allows them to add &lt;head&gt; elements (script, style, title, ...), 
                html attributes, body scripts, etc.
            </p>
            <p><a class="btn btn-default" href="http://gobline.com/docs/template-rendering#view-helpers" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>HMVC - Widgetized Content</h3>
            <p>
                The <i>Request</i> view helper allows you to include the result of a sub-request in the view.
                HMVC increases code modularity, aids re-usability, and maintains a better separation of concerns.
            </p>
            <p><a class="btn btn-default" href="http://gobline.com/docs/template-rendering#hmvc" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>Great Multilingual Support</h3>
            <p>
                Building multilingual applications has never been so easy:
                the language is automatically fetched from the URL, URL segments can be translated in any language with the bundled I18N routers and view helpers allow you to add the necessary HTML metadata for the current language in use.
            </p>
            <p><a class="btn btn-default" href="http://gobline.com/docs/routing#i18n" role="button">Read more &raquo;</a></p>
        </div>
    </div>

    <div class="row">

        <div class="col-md-4">
            <h3>A Better MVC Approach</h3>
            <p>
                According to the original MVC pattern, the controller should not interact with the view.
                Though, all major frameworks seem to contradict this rule.
                Gobline's MVC design tend to follow the original pattern with the use of <i>Action Models</i> and HMVC.
            </p>
            <p><a class="btn btn-default" href="http://gobline.com/docs/concepts/mvc/controller" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>Loosely Coupled Components</h3>
            <p>
                Gobline is composed of a set of loosely coupled components that can be used 
                out of the context of an MVC application.
            </p>
            <p><a class="btn btn-default" href="http://gobline.com/docs/components" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>PHP-FIG</h3>
            <p>
                Gobline follows the PHP Framework Interop Group standards closely.
                The core application is solely composed of a set of PSR-7 middlewares.
            </p>
        </div>
    </div>

    <h2 class="text-primary">What else?</h2>
    <br>

    <div class="row">
        <div class="col-md-4">
            <h3>Straightforward ACL/Auth Component</h3>
            <p>
                You can implement ACL rules on your routes without efforts. 
                Do you have an admin area? Secure access to <i>/admin</i> for administrators only,
                via a simple config rule.
            </p>
            <p><a class="btn btn-default" href="http://gobline.com/docs/middlewares#default-middlewares" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>Convenient Composite Loggers</h3>
            <p>
                Gobline comes with a set of loggers that you can combine 
                for a specific log level.<br>
                Log your messages into your DB, as an email, or you can even tweet them 
                to yourself to take advantage of instant mobile notifications.
            </p>
            <p><a class="btn btn-default" href="http://gobline.com/docs/components" role="button">Read more &raquo;</a></p>
        </div>

        <div class="col-md-4">
            <h3>Powerful Input Filters</h3>
            <p>
                Validators and sanitizers help filtering input data.
                Filter funnels allow you to filter a variable through multiple sanitizers and validators at once.
                The <i>Escape</i> helper allows you to escape data in your HTML-templates.<br>
                Input data should be validated/sanitized as soon as possible and escaped as late as possible.
            </p>
            <p><a class="btn btn-default" href="http://gobline.com/docs/components" role="button">Read more &raquo;</a></p>
        </div>
    </div>

    <hr>

    <footer>
        <p>&copy; Gobline 2015</p>
    </footer>
</div> <!-- /container -->